version: '3.2'
services: 
    jenkins:
        image: jenkins/jenkins:lts
        privileged: true
        user: root
        ports: 
            - 8081:8080
            - 5000:5000
        container_name: jenkins
        volumes: 
            - /tmp/jenkis:/var/jenkins_home
            - /var/run/docker.sock:/var/run/docker.sock
            - /usr/local/bin/docker:/usr/local/bin/docker